<?php

namespace AppBundle\Repository;

/**
 * CoachUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachUserRepository extends \Doctrine\ORM\EntityRepository
{
}
