<?php

namespace AppBundle\Repository;

/**
 * TesteurUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesteurUserRepository extends \Doctrine\ORM\EntityRepository
{
}
