<?php

namespace AppBundle\Repository;

/**
 * TuteurUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TuteurUserRepository extends \Doctrine\ORM\EntityRepository
{
}
