# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ 'ROLE_USER', 'ROLE_SONATA_ADMIN' ]
        ROLE_SUPER_ADMIN: [ 'ROLE_ADMIN', 'ROLE_ALLOWED_TO_SWITCH' ]
        # a clean a la fin
        ROLE_USER: [ 'ROLE_USER', 'ROLE_SONATA_ADMIN', 'ROLE_SUPER_ADMIN' ]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            remember_me:
                secret:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                success_handler: AppBundle\Handler\AuthenticationHandler
                failure_handler: AppBundle\Handler\AuthenticationHandler
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /


    access_control:
        #- { path: ^/admin/, role: ['ROLE_ADMIN', 'ROLE_SONATA_ADMIN'] }
        - { path: ^/admin/, role: 'ROLE_USER' }